<?php
	
	$designare_general_options= array( array(
		"name" => "Newsletter",
		"type" => "title",
		"img" => DESIGNARE_IMAGES_URL."icon_general.png"
	),
	
	array(
		"type" => "open",
		"subtitles"=>array(array("id"=>"newsletter", "name"=>"Newsletter Code"))
	),
	
	
	
	/* ------------------------------------------------------------------------*
	 * Top Panel
	 * ------------------------------------------------------------------------*/
	
	array(
		"type" => "subtitle",
		"id"=>'newsletter'
	),
	
	array(
		"type" => "documentation",
		"text" => "<h3>Mail Chimp Newsletter</h3>"
	),
	
	array(
		"name" => "Newsletter <b>First Text</b>",
		"id" => DESIGNARE_SHORTNAME."_newsletter_text",
		"type" => "text",
		"desc" => "Set the <b>Subscribe Now</b> text.<br/> NOTE: If you add links, span or class <b>do not use quotes or double quotes</b>.<br/> ex: < span class=text_color > ",
		'std' => 'Subscribe our <span class=text_color>Newsletter</span>'
	),
	
	array(
		"name" => "Newsletter <b>Second Text</b>",
		"id" => DESIGNARE_SHORTNAME."_newsletter_stext",
		"type" => "text",
		"desc" => "Set the Newsletter Second text",
		'std' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since"
	),

	array(
		"name" => "Newsletter <i>Input</i> text",
		"id" => DESIGNARE_SHORTNAME."_newsletter_input_text",
		"type" => "text",
		"desc" => "Set the <i>Enter your e-mail</i> text",
		'std' => 'ENTER YOUR EMAIL HERE'
	),

		
	array(
		"name" => "Mail Chimp Code",
		"id" => DESIGNARE_SHORTNAME."_mailchimp_code",
		"type" => "textarea",
		"desc" => "Use this textbox to paste the code generated by MailChimp.<br/>Create Form > Share It > Click - Create HTML code for a small subscribe form",
		"std" => '<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="http://designarethemes.us6.list-manage.com/subscribe/post?u=160d66f0029484b9fa1706377&id=4d5b5b8577" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>	<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>

<!--End mc_embed_signup-->'
	),

	array(
		"type" => "close"
	),
	
	/*close array*/
	
	array(
		"type" => "close"
	));
	
	designare_add_options($designare_general_options);
	
?>